### ISSUE TITLE
Finished

### ISSUE THREAD

**Issue by nozerorma** [nozerorma/decont#2]
Hello @tdido 

So I finished the script. I have a few doubts, namely:

the md5sum check in the download script (l11 onewards), as I created a verification tmp file and used cd, both of which I didn't want to do.
```
echo -e "Veryfing download integrity...\n" # md5sum verification
	cd $directoryurl
	curl ${downloadurl}.md5 | md5sum -c --ignore-missing > verifiedmd5.tmp
	if grep OK *.tmp 
	then
        	echo -e "Download integrity verified\n"
        	rm *.tmp
        	cd ..
	else
		echo -e "Download integrity could not be verified. Aborting...\n"
		cd ..
		bash scripts/cleanup.sh Y
		echo -e "\n############ Pipeline failed at $(date +'%H:%M:%S') ##############\n"
		exit 1
	fi
```
Cleanup script also took me a while to understand, with quite a few fuckups and repo clones. Luckily I've been committing quite often.
For the rest, if you see something weird please let me know.

I'll be trying to do the oneliner wget but I am quite happy with the results I obtanined.

**Comment by nozerorma** [comment]
Also, in the main pipeline, I tried to make a common log, which works, but it is bulky and ugly. I was looking for a way to redirect many grep calls at once to a file but I couldn't find how.
```
echo -e "\nSaving a common log with information on trimming and alignment results...\n"

# I don't like this approach, search alt
echo -e "\nGlobal log input as of $(date +'%x                %H:%M:%S')\n" >> pipeline.log
echo >> pipeline.log
for basenameSid in $(find out/trimmed -name \* -type f -exec basename {} .fastq.gz \; | cut -d"_" -f-2)
do
        echo -e "$basenameSid STAR analysis\n" >> pipeline.log
        grep 'Uniquely mapped reads %' out/star/$basenameSid/Log.final.out | \
		awk -v OFS=' ' '{$1=$1}1' >> pipeline.log
        grep '% of reads mapped to too many loci' out/star/$basenameSid/Log.final.out | \
		awk -v OFS=' ' '{$1=$1}1' >> pipeline.log
        grep '% of reads mapped to multiple loci' out/star/$basenameSid/Log.final.out | \
		awk -v OFS=' ' '{$1=$1}1' >> pipeline.log
	echo >> pipeline.log
	echo -e "$basenameSid cutadapt analysis\n" >> pipeline.log
        grep 'Reads with adapters' log/cutadapt/$basenameSid.log | \
		awk -v OFS=' ' '{$1=$1}1' >> pipeline.log
        grep 'Total basepairs' log/cutadapt/$basenameSid.log | \
		awk -v OFS=' ' '{$1=$1}1' >> pipeline.log
        echo >> pipeline.log
done

echo -e "\n############ Pipeline finished at $(date +'%H:%M:%S') ##############\n"```

**Comment by tdido** [comment]
Preventing `cd` in the check would probably require some sort of editing of the data in the md5 file before using it, or doing everything on the fly with something like process substitution.

In any case, your solution is valid for the scope of this exercise (if it works of course, I haven't run the code yet ;))

**Comment by nozerorma** [comment]
> 'Uniquely mapped reads %'

Yup, that worked great and looks much neater
